--CREATE DATABASE dTBQT1
--USE dTBQT
--CREATE TABLE dTBQT(
--	NGUYENMAU nvarchar(225) PRIMARY KEY,
--	QUAKHUDON nvarchar(225),
--	QUAKHUPHANTU nvarchar(225),
--	NGHIA nvarchar(225)
--)
--drop table dTBQT
--DELETE FROM dTBQT


INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('abide','abode/abided','abode/abided',N'lưu trú, lưu lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('arise','arose','arisen',N'phát sinh')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('awake','awoke','awoken',N'đánh thức, thức')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('backslide','backslid','backslidden/backslid',N'tái phạm')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('be','was/were','been',N'thì, là, bị, ở')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('bear','bore','borne',N'mang, chịu đựng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('beat','beat','beaten/beat',N'đánh, đập')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('become','became','become',N'trở nên')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('befall','befell','befallen',N'xảy đến')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('begin','began','begun',N'bắt đầu')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('behold','beheld','beheld',N'ngắm nhìn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('bend','bent','bent',N'bẻ cong')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('beset','beset','beset',N'bao quanh')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('bespeak','bespoke','bespoken',N'chứng tỏ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('bet','bet/betted','bet/betted ',N'đánh cược, cá cược')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('bid','bid','bid',N'trả giá')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('bind','bound','bound',N'buộc, trói')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('bite','bit','bitten',N'cắn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('bleed','bled','bled',N'chảy máu')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('blow','blew','blown',N'thổi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('break','broke','broken',N'đập vỡ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('breed','bred','bred',N'nuôi, dạy dỗ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('bring','brought','brought',N'mang đến')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('broadcast','broadcast','broadcast',N'phát thanh')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('browbeat','browbeat','browbeaten/browbeat',N'hăm dọa')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('build','built','built',N'xây dựng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('burn','burnt/burned','burnt/burned',N'đốt, cháy')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('burst','burst','burst',N'nổ tung, vỡ òa')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('bust','busted/bust','busted/bust',N'làm bể, làm vỡ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('buy','bought','bought',N'mua')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('cast','cast','cast',N'ném, tung')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('catch','caught','caught',N'bắt, chụp')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('chide','chid/chided','chid/chidden/chided',N'mắng, chửi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('choose','chose','chosen',N'chọn, lựa')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('cleave','clove/cleft/cleaved','cloven/cleft/cleaved',N'chẻ, tách hai')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('cleave','clave','cleaved',N'dính chặt')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('cling','clung','clung',N'bám vào, dính vào')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('clothe','clothed/clad ','clothed/clad',N'che phủ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('come','came','come',N'đến, đi đến')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('cost','cost','cost',N'có giá là')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('creep','crept','crept ',N'bò, trườn, lẻn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('crossbreed','crossbred','crossbred',N'cho lai giống')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('crow','crew/crewed','crowed',N'gáy (gà)')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('cut','cut','cut',N'cắt, chặt')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('daydream','daydreamed/daydreamt','daydreamed/daydreamt',N'nghĩ vẩn vơ, mơ mộng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('deal','dealt','dealt',N'giao thiệp')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('dig','dug','dug',N'đào')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('disprove','disproved','disproved/disproven ',N'bác bỏ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('dive','dove/dived','dived',N'lặn, lao xuống')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('do','did','done',N'làm')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('draw','drew','drawn',N'vẽ, kéo')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('dream','dreamt/dreamed','dreamt/dreamed',N'mơ thấy')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('drink','drank','drunk',N'uống')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('drive','drove','driven',N'lái xe')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('dwell','dwelt','dwelt',N'trú ngụ, ở')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('eat','ate','eaten',N'ăn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('fall','fell','fallen',N'ngã, rơi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('feed','fed','fed',N'cho ăn, ăn, nuôi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('feel','felt','felt',N'cảm thấy')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('fight','fought','fought',N'chiến đấu')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('find','found','found',N'tìm thấy, thấy')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('fit','fitted/fit','fitted/fit',N'làm cho vừa, làm cho hợp')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('flee','fled','fled',N'chạy trốn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('fling','flung','flung',N'tung, quăng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('fly','flew','flown',N'bay')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('forbear','forbore','forborne',N'nhịn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('forbid','forbade/forbad','forbidden',N'cấm, cấm đoán')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('forecast','forecast/forecasted','forecast/forecasted',N'tiên đoán')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('forego (also forgo)','forewent','foregone',N'bỏ, kiêng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('foresee','foresaw','forseen',N'thấy trước')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('foretell','foretold','foretold',N'đoán trước')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('forget','forgot','forgotten',N'quên')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('forgive','forgave','forgiven',N'tha thứ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('forsake','forsook','forsaken',N'ruồng bỏ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('freeze','froze','frozen',N'(làm) đông lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('frostbite','frostbit','frostbitten',N'bỏng lạnh')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('get','got','got/gotten',N'có được')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('gild','gilt/gilded','gilt/gilded',N'mạ vàng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('gird','girt/girded','girt/girded',N'đeo vào')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('give','gave','given',N'cho')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('go','went','gone',N'đi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('grind','ground','ground',N'nghiền, xay')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('grow','grew','grown',N'mọc, trồng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('hand-feed','hand-fed','hand-fed',N'cho ăn bằng tay')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('handwrite','handwrote','handwritten',N'viết tay')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('hang','hung','hung',N'móc lên, treo lên')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('have','had','had',N'có')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('hear','heard','heard',N'nghe')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('heave','hove/heaved','hove/heaved',N'trục lên')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('hew','hewed','hewn/hewed',N'chặt, đốn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('hide','hid','hidden',N'giấu, trốn, nấp')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('hit','hit','hit',N'đụng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('hurt','hurt','hurt',N'làm đau')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('inbreed','inbred','inbred',N'lai giống cận huyết')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('inlay','inlaid','inlaid',N'cẩn, khảm')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('input','input','input',N'đưa vào')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('inset','inset','inset',N'dát, ghép')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('interbreed','interbred','interbred',N'giao phối, lai giống')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('interweave','interwove/interweaved','interwoven/interweaved',N'trộn lẫn, xen lẫn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('interwind','interwound','interwound',N'cuộn vào, quấn vào')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('jerry-build','jerry-built','jerry-built',N'xây dựng cẩu thả')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('keep','kept','kept',N'giữ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('kneel','knelt/kneeled','knelt/kneeled',N'quỳ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('knit','knit/knitted','knit/knitted',N'đan')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('know','knew','known',N'biết, quen biết')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('lay','laid','laid',N'đặt, để')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('lead','led','led',N'dẫn dắt, lãnh đạo')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('lean','leaned/leant ','leaned/leant ',N'dựa, tựa')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('leap','leapt','leapt',N'nhảy, nhảy qua')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('learn','learnt/learned','learnt/learned',N'học, được biết')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('leave','left','left',N'ra đi, để lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('lend','lent','lent',N'cho mượn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('let','let','let',N'cho phép, để cho')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('lie','lay','lain',N'nằm')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('light','lit/lighted','lit/lighted',N'thắp sáng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('lip-read','lip-read','lip-read',N'mấp máy môi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('lose','lost','lost',N'làm mất, mất')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('make','made','made',N'chế tạo, sản xuất')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('mean','meant','meant',N'có nghĩa là')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('meet','met','met',N'gặp mặt')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('miscast','miscast','miscast',N'chọn vai đóng không hợp')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('misdeal','misdealt','misdealt',N'chia lộn bài, chia bài sai')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('misdo','misdid','misdone',N'phạm lỗi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('mishear','misheard','misheard',N'nghe nhầm')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('mislay','mislaid','mislaid',N'để lạc mất')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('mislead','misled','misled',N'làm lạc đường')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('mislearn','mislearned/mislearnt','mislearned/mislearnt',N'học nhầm')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('misread','misread','misread',N'đọc sai')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('misset','misset','misset ',N'đặt sai chỗ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('misspeak','misspoke','misspoken',N'nói sai')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('misspell','misspelt','misspelt',N'viết sai chính tả')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('misspend','misspent','misspent',N'tiêu phí, bỏ phí')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('mistake','mistook','mistaken',N'phạm lỗi, lầm lẫn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('misteach','mistaught','mistaught',N'dạy sai')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('misunderstand','misunderstood','misunderstood',N'hiểu lầm')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('miswrite','miswrote','miswritten',N'viết sai')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('mow','mowed','mown/mowed',N'cắt cỏ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('offset','offset','offset',N'đền bù')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outbid','outbid','outbid',N'trả hơn giá')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outbreed','outbred','outbred',N'giao phối xa')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outdo','outdid','outdone',N'làm giỏi hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outdraw','outdrew','outdrawn',N'rút súng ra nhanh hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outdrink','outdrank','outdrunk',N'uống quá chén')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outdrive','outdrove','outdriven',N'lái nhanh hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outfight','outfought','outfought',N'đánh giỏi hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outfly','outflew','outflown',N'bay cao/xa hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outgrow','outgrew','outgrown',N'lớn nhanh hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outleap','outleaped/outleapt ','outleaped/outleapt',N'nhảy cao/xa hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outlie','outlied','outlied',N'nói dối')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('output','output','output',N'cho ra (dữ kiện)')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outride','outrode','outridden',N'cưỡi ngựa giỏi hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outrun','outran','outrun',N'chạy nhanh hơn, vượt giá')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outsell','outsold','outsold',N'bán nhanh hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outshine','outshined/outshone ','outshined/outshone',N'sáng hơn, rạng rỡ hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outshoot','outshot','outshot ',N'bắn giỏi hơn, nảy mầm, mọc')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outsing','outsang','outsung',N'hát hay hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outsit','outsat','outsat',N'ngồi lâu hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outsleep','outslept','outslept',N'ngủ lâu/muộn hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outsmell','outsmelled/outsmelt ','outsmelled/outsmelt',N'khám phá, đánh hơi, sặc mùi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outspeak','outspoke','outspoken ',N'nói nhiều/dài/to hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outspeed','outsped','outsped',N'đi/chạy nhanh hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outspend','outspent','outspent',N'tiêu tiền nhiều hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outswear','outswore','outsworn',N'nguyền rủa nhiều hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outswim','outswam','outswum',N'bơi giỏi hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outthink','outthought','outthought',N'suy nghĩ nhanh hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outthrow','outthrew','outthrown',N'ném nhanh hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('outwrite','outwrote','outwritten',N'viết nhanh hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overbid','overbid','overbid',N'trả giá/bỏ thầu cao hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overbreed','overbred','overbred',N'nuôi quá nhiều')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overbuild','overbuilt','overbuilt',N'xây quá nhiều')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overbuy','overbought','overbought',N'mua quá nhiều')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overcome','overcame','overcome',N'khắc phục')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overdo','overdid','overdone',N'dùng quá mức, làm quá')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overdraw','overdrew','overdrawn',N'rút quá số tiền, phóng đại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overdrink','overdrank','overdrunk',N'uống quá nhiều')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overeat','overate','overeaten',N'ăn quá nhiều')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overfeed','overfed','overfed',N'cho ăn quá mức')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overfly','overflew','overflown',N'bay qua')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overhang','overhung','overhung',N'nhô lên trên, treo lơ lửng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overhear','overheard','overheard',N'nghe trộm')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overlay','overlaid','overlaid',N'phủ lên')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overpay','overpaid','overpaid',N'trả quá tiền')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('override','overrode','overridden',N'lạm quyền')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overrun','overran','overrun',N'tràn ngập')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('oversee','oversaw','overseen',N'trông nom')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('oversell','oversold','oversold',N'bán quá mức')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('oversew','oversewed','oversewn/oversewed',N'may nối vắt')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overshoot','overshot','overshot',N'đi quá đích')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('oversleep','overslept','overslept',N'ngủ quên')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overspeak','overspoke','overspoken',N'Nói quá nhiều, nói lấn át')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overspend','overspent','overspent',N'tiêu quá lố')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overspill','overspilled/overspilt','overspilled/overspilt',N'đổ, làm tràn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overtake','overtook','overtaken',N'đuổi bắt kịp')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overthink','overthought','overthought',N'tính trước nhiều quá')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overthrow','overthrew','overthrown',N'lật đổ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overwind','overwound','overwound',N'lên dây (đồng hồ) quá chặt')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('overwrite','overwrote','overwritten',N'viết dài quá, viết đè lên')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('partake','partook','partaken',N'tham gia, dự phần')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('pay','paid','paid',N'trả (tiền)')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('plead','pleaded/pled','pleaded/pled',N'bào chữa, biện hộ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('prebuild','prebuilt','prebuilt',N'làm nhà tiền chế')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('predo','predid','predone',N'làm trước')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('premake','premade','premade',N'làm trước')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('prepay','prepaid','prepaid',N'trả trước')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('presell','presold','presold',N'bán trước thời gian rao báo')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('preset','preset','preset',N'thiết lập sẵn, cài đặt sẵn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('preshrink','preshrank','preshrunk',N'ngâm cho vải co trước khi may')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('proofread','proofread','proofread',N'Đọc bản thảo trước khi in')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('prove','proved','proven/proved',N'chứng minh')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('put','put','put',N'đặt, để')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('quick-freeze','quick-froze','quick-frozen',N'kết đông nhanh')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('quit','quit/quitted ','quit/quitted',N'bỏ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('read','read ','read',N'đọc')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('reawake','reawoke','reawaken',N'đánh thức 1 lần nữa')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rebid','rebid','rebid',N'trả giá, bỏ thầu')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rebind','rebound','rebound',N'buộc lại, đóng lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rebroadcast','rebroadcast/rebroadcasted','rebroadcast/rebroadcasted',N'cự tuyệt, khước từ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rebuild','rebuilt','rebuilt',N'xây dựng lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('recast','recast','recast',N'đúc lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('recut','recut','recut',N'cắt lại, băm)')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('redeal','redealt','redealt',N'phát bài lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('redo','redid','redone',N'làm lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('redraw','redrew','redrawn',N'kéo ngược lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('refit','refitted/refit ','refitted/refit',N'luồn, xỏ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('regrind','reground','reground',N'mài sắc lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('regrow','regrew','regrown',N'trồng lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rehang','rehung','rehung',N'treo lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rehear','reheard','reheard',N'nghe trình bày lại ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('reknit','reknitted/reknit','reknitted/reknit',N'đan lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('relay','relaid','relaid',N'đặt lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('relay ','relayed','relayed',N'truyền âm lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('relearn','relearned/relearnt','relearned/relearnt ',N'học lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('relight','relit/relighted','relit/relighted',N'thắp sáng lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('remake','remade','remade',N'làm lại, chế tạo lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rend','rent','rent',N'toạc ra, xé')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('repay','repaid','repaid',N'hoàn tiền lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('reread','reread','reread',N'đọc lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rerun','reran','rerun',N'chiếu lại, phát lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('resell','resold','resold',N'bán lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('resend','resent','resent',N'gửi lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('reset','reset','reset',N'đặt lại, lắp lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('resew','resewed','resewn/resewed',N'may/khâu lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('retake','retook','retaken',N'chiếm lại,tái chiếm')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('reteach','retaught','retaught',N'dạy lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('retear','retore','retorn',N'khóc lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('retell','retold','retold',N'kể lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rethink','rethought','rethought',N'suy tính lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('retread','retread','retread',N'lại giẫm/đạp lên')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('retrofit','retrofitted/retrofit ','retrofitted/retrofit',N'trang bị thêm những bộ phận mới')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rewake','rewoke/rewaked','rewaken/rewaked ',N'đánh thức lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rewear','rewore','reworn',N'mặc lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('reweave','rewove/reweaved','rewoven/reweaved',N'dệt lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rewed','rewed/rewedded','rewed/rewedded',N'kết hôn lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rewet','rewet/rewetted','rewet/rewetted',N'làm ướt lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rewin','rewon','rewon',N'thắng lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rewind','rewound','rewound',N'cuốn lại, lên dây lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rewrite','rewrote','rewritten',N'viết lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rid','rid','rid',N'giải thoát')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('ride','rode','ridden',N'cưỡi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('ring','rang','rung',N'rung chuông')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('rise','rose','risen',N'đứng dậy, mọc')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('roughcast','roughcast','roughcast',N'tạo hình phỏng chừng ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('run','ran','run',N'chạy')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sand-cast','sand-cast','sand-cast',N'đúc bằng khuôn cát')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('saw','sawed','sawn',N'cưa')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('say','said','said',N'nói')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('see','saw','seen',N'nhìn thấy')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('seek','sought','sought',N'tìm kiếm')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sell','sold','sold',N'bán')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('send','sent','sent',N'gửi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('set','set','set',N'đặt, thiết lập')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sew','sewed','sewn/sewed',N'may')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('shake','shook','shaken',N'lay, lắc')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('shave','shaved','shaved/shaven',N'cạo (râu, mặt)')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('shear','sheared','shorn',N'xén lông (cừu)')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('shed','shed','shed',N'rơi, rụng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('shine','shone','shone',N'chiếu sáng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('shit','shit/shat/shitted','shit/shat/shitted',N'suộc khuộng đi đại tiện')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('shoot','shot','shot',N'bắn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('show','showed','shown/showed',N'cho xem')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('shrink','shrank','shrunk',N'co rút')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('shut','shut','shut',N'đóng lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sight-read','sight-read','sight-read',N'chơi hoặc hát mà không cần nghiên cứu trước')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sing','sang','sung',N'ca hát')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sink','sank','sunk',N'chìm, lặn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sit','sat','sat',N'ngồi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('slay','slew','slain',N'sát hại, giết hại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sleep','slept','slept',N'ngủ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('slide','slid','slid',N'trượt, lướt')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sling','slung','slung',N'ném mạnh')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('slink','slunk','slunk',N'lẻn đi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('slit','slit','slit',N'rạch, khứa')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('smell','smelt','smelt',N'ngửi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('smite','smote','smitten',N'đập mạnh')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sneak','sneaked/snuck','sneaked/snuck',N'trốn, lén')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('speak','spoke','spoken',N'nói')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('speed','sped/speeded','sped/speeded',N'chạy vụt')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('spell','spelt/spelled','spelt/spelled',N'đánh vần')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('spend','spent','spent',N'tiêu xài')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('spill','spilt/spilled','spilt/spilled',N'tràn, đổ ra')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('spin','spun/span','spun',N'quay sợi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('spoil','spoilt/spoiled','spoilt/spoiled',N'làm hỏng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('spread','spread','spread',N'lan truyền')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('stand','stood','stood',N'đứng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('steal','stole','stolen',N'đánh cắp')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('stick','stuck','stuck',N'ghim vào, đính')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sting','stung','stung',N'châm, chích, đốt')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('stink','stunk/stank','stunk',N'bốc mùi hôi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('stride','strode','stridden',N'bước sải')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('strike','struck','struck',N'đánh đập')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('string','strung','strung',N'gắn dây vào')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sunburn','sunburned/sunburnt ','sunburned/sunburnt',N'cháy nắng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('swear','swore','sworn',N'tuyên thệ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sweat','sweat/sweated','sweat/sweated ',N'đổ mồ hôi')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('sweep','swept','swept',N'quét')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('swell','swelled','swollen/swelled',N'phồng, sưng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('swim','swam','swum',N'bơi lội')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('swing','swung','swung',N'đong đưa')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('take','took','taken',N'cầm, lấy')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('teach','taught','taught',N'dạy, giảng dạy')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('tear','tore','torn',N'xé, rách')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('telecast','telecast','telecast',N'phát đi bằng truyền hình')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('tell','told','told',N'kể, bảo')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('think','thought','thought',N'suy nghĩ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('throw','threw','thrown',N'ném,, liệng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('thrust','thrust','thrust',N'thọc, nhấn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('tread','trod','trodden/trod',N'giẫm, đạp')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('typewrite','typewrote','typewritten',N'đánh máy')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('unbend','unbent','unbent',N'làm thẳng lại')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('unbind','unbound','unbound',N'mở, tháo ra')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('unclothe','unclothed/unclad ','unclothed/unclad',N'cởi áo, lột trần')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('undercut','undercut','undercut',N'ra giá rẻ hơn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('underfeed','underfed','underfed',N'cho ăn đói, thiếu ăn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('undergo','underwent','undergone',N'kinh qua')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('underlie','underlay','underlain',N'nằm dưới')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('understand','understood','understood',N'hiểu')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('undertake','undertook','undertaken',N'đảm nhận')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('underwrite','underwrote','underwritten',N'bảo hiểm')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('undo','undid','undone',N'tháo ra')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('unfreeze','unfroze','unfrozen',N'làm tan đông')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('unhang','unhung','unhung',N'hạ xuống, bỏ xuống')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('unhide','unhid','unhidden',N'hiển thị, không ẩn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('unlearn','unlearned/unlearnt ','unlearned/unlearnt',N'gạt bỏ, quên')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('unspin','unspun','unspun',N'quay ngược')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('unwind','unwound','unwound',N'tháo ra')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('uphold','upheld','upheld',N'ủng hộ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('upset','upset','upset',N'đánh đổ, lật đổ')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('wake','woke/waked','woken/waked',N'thức giấc')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('wear','wore','worn',N'mặc')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('wed','wed/wedded','wed/wedded',N'kết hôn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('weep','wept','wept',N'khóc')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('wet','wet/wetted','wet/wetted',N'làm ướt')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('win','won','won',N'thắng, chiến thắng')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('wind','wound','wound',N'quấn')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('withdraw','withdrew','withdrawn',N'rút lui')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('withhold','withheld','withheld',N'từ khước')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('withstand','withstood','withstood',N'cầm cự')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('work','worked','worked',N'rèn, nhào nặn đất')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('wring','wrung','wrung',N'vặn, siết chặt')
INSERT INTO dTBQT(NGUYENMAU,QUAKHUDON,QUAKHUPHANTU,NGHIA) VALUES ('write','wrote','written',N'viết')
